import { Inter } from "next/font/google";
import "./globals.css";
import App from "./App";
import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth";
import Signin from "./components/AuthScreen/Signin";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth()

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {session ? <App>{children}</App> : <Signin />}
          {/* sdfsfs */}
          {/* <App>{children}</App> */}
        </SessionProvider>
      </body>
    </html>
  );
}
